CREATE TABLE region (
    id      NUMBER  GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY ,
    name    VARCHAR2(15) NOT NULL
)
INSERT INTO region (name) VALUES ('Ahmadli');
INSERT INTO region (name) VALUES ('Baku');
INSERT INTO region (name) VALUES ('Binagadi');
INSERT INTO region (name) VALUES ('Garadagh');
INSERT INTO region (name) VALUES ('Khazarregion');
INSERT INTO region (name) VALUES ('Nasimi');
INSERT INTO region (name) VALUES ('Nizami');
INSERT INTO region (name) VALUES ('Khatai');

--------------------------------------------------------------------------------------------------------------

CREATE TABLE subject (
    id      NUMBER  GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY ,
    name    VARCHAR2(16) NOT NULL
)

INSERT INTO subject (name) VALUES ('Azerbaycan dili');
INSERT INTO subject (name) VALUES ('Xarici dil');
INSERT INTO subject (name) VALUES ('Hendese');
INSERT INTO subject (name) VALUES ('Riyaziyyat');
INSERT INTO subject (name) VALUES ('Fizika');
INSERT INTO subject (name) VALUES ('Kimya');
INSERT INTO subject (name) VALUES ('Fiziki Terbiye');
INSERT INTO subject (name) VALUES ('Musiqi');

--------------------------------------------------------------------------------------------------------------

CREATE TABLE teacher (
    -- id      NUMBER  GENERATED ALWAYS AS IDENTITY  PRIMARY KEY ,
    id           NUMBER  GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY ,
    name         VARCHAR2(15) NOT NULL,
    surname      VARCHAR2(15) NOT NULL,
    age          NUMBER(3) NOT NULL,
    phone        CHAR(10) NOT NULL,
    subject_id   NUMBER(2) NOT NULL,
    
    CONSTRAINT fk_subject
    FOREIGN KEY(subject_id)
    REFERENCES subject(id)
);

INSERT INTO teacher (name,surname,age,phone,subject_id) VALUES ('Xalid','Muradli',40,0509026752,1);
INSERT INTO teacher (name,surname,age,phone,subject_id) VALUES ('Bilal','Cahangirlü',30,0502411587,6);
INSERT INTO teacher (name,surname,age,phone,subject_id) VALUES ('Haci','Familoglu',25,0502154594,5);
INSERT INTO teacher (name,surname,age,phone,subject_id) VALUES ('Bextiyar','Ibrahimov',41,0509081478,2);
INSERT INTO teacher (name,surname,age,phone,subject_id) VALUES ('Etibar','Adigozalov',31,0554868283,7);
INSERT INTO teacher (name,surname,age,phone,subject_id) VALUES ('Elxan','Guliyeva',45,0519026752,8);
INSERT INTO teacher (name,surname,age,phone,subject_id) VALUES ('Sadix','Alakbarov',47,0106229833,4);
INSERT INTO teacher (name,surname,age,phone,subject_id) VALUES ('Etibar','Allahyarov',45,0500714220,3);

--------------------------------------------------------------------------------------------------------------

CREATE TABLE student (
    id      NUMBER  GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY ,
    name    VARCHAR2(15) NOT NULL,
    surname VARCHAR2(15) NOT NULL,
    age     NUMBER(2) NOT NULL,
    teacher_id NUMBER(2) NOT NULL,
    region_id  NUMBER(2) NOT NULL,
    
    CONSTRAINT fk_teacher
    FOREIGN KEY(teacher_id)
    REFERENCES teacher(id),
    
    CONSTRAINT fk_region
    FOREIGN KEY(region_id)
    REFERENCES region(id)                                      
);

INSERT INTO student (name,surname,age,teacher_id,region_id) VALUES ('Vaqif','Gasimov',11,3,1);
INSERT INTO student (name,surname,age,teacher_id,region_id) VALUES ('Asiman','Teymurlü',15,1,6);
INSERT INTO student (name,surname,age,teacher_id,region_id) VALUES ('Mahir','Aliyev',14,7,5);
INSERT INTO student (name,surname,age,teacher_id,region_id) VALUES ('Allahverdi','Heybatov',16,6,2);
INSERT INTO student (name,surname,age,teacher_id,region_id) VALUES ('Fazil','Alakbarov',17,4,3);
INSERT INTO student (name,surname,age,teacher_id,region_id) VALUES ('Muxtar','Abahadili',10,2,2);
INSERT INTO student (name,surname,age,teacher_id,region_id) VALUES ('Urfan','Bahlulov',16,5,8);
INSERT INTO student (name,surname,age,teacher_id,region_id) VALUES ('Nicat','Betiyaroglu',11,7,7);

--------------------------------------------------------------------------------------------------------------

--Select table
select *from teacher;
select *from student;
select *from region;
select *from subject;
--------------------------------------------------------------------------------------------------------------

--Drop tables
drop table teacher;
drop table student;
drop table region;
drop table subject;
--------------------------------------------------------------------------------------------------------------

--Truncate tables
truncate table teacher;
truncate table student;
truncate table region;
truncate table subject;
--------------------------------------------------------------------------------------------------------------

--Inner join(student,region)
select s.id,s.name AD,s.surname SOYAD,s.age YAS,r.name "YASADIGI UNVAN" from student s inner join region r on s.region_id=r.id;

--Inner join(teacher,subjecct)
select t.id,t.name AD,t.surname SOYAD,t.age YAS,t.phone TELEFON,s.name "TEDRIS ETDIYI FENN" from teacher t inner join subject s on t.subject_id=s.id;
                        
--Inner join(student,region,teacher)                
select s.id,s.name AD,s.surname SOYAD,s.age YAS,r.name "YASADIGI UNVAN",t.name "SINIF REHBER AD",t.surname "SINIF REHBER SOYAD" from student s inner join region r on s.region_id=r.id 
            inner join teacher t on s.teacher_id=t.id;

--Inner join(student,region,teacher,subject)                      
select s.id,s.name AD,s.surname SOYAD,s.age YAS,r.name "YASADIGI UNVAN",t.name "SINIF REHBER AD",t.surname "SINIF REHBER SOYAD",subject.name Sinif_Rehber_Fenn from student s inner join region r on s.region_id=r.id 
            inner join teacher t on s.teacher_id=t.id
            inner join subject on t.subject_id=subject.id;
                        
                   



















